version: 2
updates:
  - package-ecosystem: pip
    directory: "/project_name"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/project_name/.github/workflows"
    schedule:
      interval: daily
