name: Pre-commit auto-update

on:
  # every monday at midnight
  schedule:
    - cron: "0 0 * * 1"
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Update pre-commit
        shell: bash
        run: |
          pip install pre-commit
          cd project_name
          pre-commit autoupdate --repo https://github.com/astral-sh/ruff-pre-commit --repo https://github.com/pre-commit/pre-commit-hooks

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
